### ISSUE TITLE
Supported language codes?

### ISSUE THREAD

**Issue by tjmille2** [terryyin/google-translate-python#21]
The example code is for chinese
translator= Translator(to_lang="zh")
translation = translator.translate("This is a pen.")

But what are the codes for the other languages?

Thanks

**Comment by baboosh** [comment]
Most language codes work as far as I know (I've tested french, spanish, chinese and japanese) If you want to find codes just search up "[language] 2 letter language code"

(fr, es, zh, ja) <-- The language codes I've referenced above

**Comment by terryyin** [comment]
It seems to follow https://en.wikipedia.org/wiki/ISO_639-1.

Added to readme. Therefore I'm closing this issue. Thanks!
