### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Bachstelze** [terryyin/google-translate-python#23]
add a valid email adress to get 10 times more translations a day with &de=%s

**Comment by terryyin** [comment]
could you please send a pull request?

**Comment by Bachstelze** [comment]
I made a suggestion.
Systran and Yandex are offering also limited free translations ;)

**Comment by terryyin** [comment]
Thanks! I will try to accept the pull request. Tests need to come alone timely:-)

Will close this issue when I'm done.

**Comment by Bachstelze** [comment]
what is now the status of the issue?

**Comment by terryyin** [comment]
I think the pull request https://github.com/terryyin/google-translate-python/pull/30 has covered the multiple provider issue. Could you check if that fit your need?

**Comment by Bachstelze** [comment]
looks good, update the readMe and i'm happy
