### ISSUE TITLE
Completely wrong results

### ISSUE THREAD

**Issue by andrewsanchez** [terryyin/google-translate-python#24]
Have you ever gotten results that were just completely bonkers?  Example:

```bash
~ $ translate -f nl -t en "Ik geloof het niet"
Pienso que no.
```

I thought it must have been a bug in your script, but I get the same results here:
http://mymemory.translated.net/en/Autodetect/English/Ik-geloof-het-niet

Do you normally get quality translations?

**Comment by terryyin** [comment]
LOL,  created an account on translated.net <http://translated.net/> and fixed this specific translation:-)
